add_rules("mode.debug", "mode.release")

target("frelayTest")
    set_rules("qt.console")
    add_files("msgTest.cpp", "msgTest.h", "protocolTest.cpp")
    add_files("infoTest.cpp", "infoTest.h")
    add_deps("ClientCore")
    add_deps("Protocol")
    add_deps("Util")
    add_frameworks("QtNetwork")

target("frelayBaseTest")
    set_rules("qt.console")
    add_files("BaseTest.cpp")
    add_deps("ClientCore")
    add_deps("Protocol")
    add_deps("Util")
    add_frameworks("QtNetwork")